[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

dotenv = ".env"
viaIr = true
optimizer = true
optimizer_runs = 1000000
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


[rpc_endpoints]
amoy = "https://polygon-amoy.g.alchemy.com/v2/${ALCHEMY_KEY}"



[etherscan]
polygon-amoy = { key = "${POLYGON_SCAN_KEY}" }


